/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Phase 2 Master Palette: Soft Retro Organic Editorial
        'bg': 'var(--bg, #F4EFE6)',
        'surface': 'var(--surface, #FBF8F2)',
        'ink': 'var(--ink, #2F4A3A)',
        'ink-deep': 'var(--ink-deep, #163323)',
        'primary': {
          DEFAULT: 'var(--primary, #C77B58)',
          hover: 'var(--primary-hover, #B26A49)',
        },
        'band': 'var(--band, #A8B89A)',
        'highlight': 'var(--highlight, #F1C9B8)',
        'muted': 'var(--muted, #536458)',

        // Soft Retro Organic Editorial Palette (bound to CSS Variables)
        'paper-bg': 'var(--color-paper-bg, #F4F0E6)',
        'dark-text': 'var(--color-dark-text, #17231A)',
        'primary-green': 'var(--color-primary-green, #315C3A)',
        'soft-green': 'var(--color-soft-green, #A9C29A)',
        'accent-yellow': 'var(--color-accent-yellow, #E5B94A)',
        'terracotta': 'var(--color-terracotta, #C96B45)',
        'pure-white': 'var(--color-pure-white, #FFFDF7)',
        
        // Semantic & System Mappings
        'grain-cream': 'var(--color-paper-bg, #F4F0E6)',
        'mandi-cream': 'var(--color-paper-bg, #F4F0E6)',
        'mandi-paper': 'var(--color-pure-white, #FFFDF7)',
        'mandi-tint': 'var(--color-mandi-tint, #EAE5D8)',
        'mandi-green': 'var(--color-primary-green, #315C3A)',
        'mandi-green-dark': 'var(--color-dark-text, #17231A)',
        'mandi-green-pale': 'var(--color-soft-green-tint, #E2EBDD)',
        'mandi-leaf': 'var(--color-primary-green, #315C3A)',
        'mandi-leaf-light': 'var(--color-soft-green, #A9C29A)',
        'mandi-charcoal': 'var(--color-dark-text, #17231A)',
        'mandi-charcoal-muted': 'var(--color-charcoal-muted, #4F6153)',
        'harvest-orange': 'var(--color-terracotta, #C96B45)',
        'harvest-orange-hover': '#B55A35',
        'harvest-orange-light': 'var(--color-terracotta-light, #F8ECE6)',
        'clay-orange': 'var(--color-terracotta, #C96B45)',
        'moss': 'var(--color-primary-green, #315C3A)',
        'pale-sage': 'var(--color-soft-green, #A9C29A)',
        'charcoal': 'var(--color-dark-text, #17231A)',
        'ink-green': 'var(--color-primary-green, #315C3A)',
        'mandi-border': 'var(--color-border-hairline, rgba(23, 35, 26, 0.12))',
        'mandi-border-dark': 'var(--color-dark-text, #17231A)',

        // Compatibility Aliases
        'farm-green': 'var(--color-primary-green, #315C3A)',
        'farm-green-dark': 'var(--color-dark-text, #17231A)',
        'farm-green-light': 'var(--color-soft-green, #A9C29A)',
        'farm-green-pale': 'var(--color-soft-green-tint, #E2EBDD)',
        'earth-green': 'var(--color-primary-green, #315C3A)',
        'warm-cream': 'var(--color-paper-bg, #F4F0E6)',
        'warm-cream-dark': 'var(--color-mandi-tint, #EAE5D8)',
        'paper-cream': 'var(--color-paper-bg, #F4F0E6)',
        'paper-white': 'var(--color-pure-white, #FFFDF7)',
        'ink-black': 'var(--color-dark-text, #17231A)',
        'blue-crate': 'var(--color-primary-green, #315C3A)',
        'citrus-yellow': 'var(--color-accent-yellow, #E5B94A)',
        'harvest-yellow': 'var(--color-accent-yellow, #E5B94A)',
        'tomato-red': 'var(--color-terracotta, #C96B45)',
        'green-beans': 'var(--color-primary-green, #315C3A)',
        'lettuce-green': 'var(--color-soft-green, #A9C29A)',
        'orange-accent': 'var(--color-terracotta, #C96B45)',
        'soil-brown': 'var(--color-primary-green, #315C3A)',
        'grain-gold': 'var(--color-accent-yellow, #E5B94A)',
      },
      fontFamily: {
        serif: ['Fraunces', 'Newsreader', 'Georgia', 'serif'],
        editorial: ['Fraunces', 'Newsreader', 'Georgia', 'serif'],
        heading: ['Fraunces', 'Newsreader', 'Georgia', 'serif'],
        retro: ['Fraunces', 'serif'],
        body: ['"DM Sans"', '"Plus Jakarta Sans"', 'Inter', '-apple-system', 'sans-serif'],
        sans: ['"DM Sans"', '"Plus Jakarta Sans"', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        sketch: ['Caveat', 'cursive'],
        grotesk: ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        '2.5xl': '20px',
        '3xl': '28px',
        '4xl': '36px',
        'pill': '9999px',
      },
      boxShadow: {
        'soft-sm': '0 4px 12px -2px rgba(23, 35, 26, 0.05)',
        'soft': '0 12px 28px -6px rgba(23, 35, 26, 0.07)',
        'soft-md': '0 16px 36px -8px rgba(23, 35, 26, 0.08)',
        'soft-lg': '0 24px 48px -12px rgba(23, 35, 26, 0.09)',
        'soft-terracotta': '0 16px 32px -8px rgba(201, 107, 69, 0.22)',
        'editorial': '0 4px 16px -2px rgba(23, 35, 26, 0.06)',
        'editorial-md': '0 12px 28px -6px rgba(23, 35, 26, 0.08)',
        'tactile': '0 8px 20px -4px rgba(23, 35, 26, 0.08)',
        'tactile-sm': '0 4px 12px -2px rgba(23, 35, 26, 0.06)',
        'tactile-lg': '0 16px 32px -8px rgba(23, 35, 26, 0.10)',
        'tactile-clay': '0 8px 20px -4px rgba(201, 107, 69, 0.20)',
        'brutal': '0 8px 20px -4px rgba(23, 35, 26, 0.08)',
        'brutal-sm': '0 4px 12px -2px rgba(23, 35, 26, 0.06)',
        'brutal-lg': '0 16px 32px -8px rgba(23, 35, 26, 0.10)',
      },
      borderWidth: {
        'hairline': '1px',
        '1.5': '1.5px',
        '2.5': '2px',
        '3': '2px',
      }
    },
  },
  plugins: [],
}
